name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  matrix-checks:
    name: Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Test
        run: pnpm test:run

      - name: Format check
        run: pnpm format:check

      - name: Build
        run: pnpm build

      - name: Pack dry run
        run: pnpm pack:dry

  test:
    name: test
    needs: matrix-checks
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Verify matrix status
        run: |
          if [ "${{ needs.matrix-checks.result }}" != "success" ]; then
            echo "Required matrix jobs failed"
            exit 1
          fi
